# Generated by Django 3.2.9 on 2021-11-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'managed': False},
        ),
    ]
