# Generated by Django 3.2.9 on 2021-11-25 15:37

import board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_alter_faqcomment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqpost',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=board.models.faq_directory_path),
        ),
    ]
