# Generated by Django 3.2.9 on 2021-11-26 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqcomment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='faqpost',
            options={'managed': False},
        ),
    ]
